global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    -   job_name: 'app'
        static_configs:
            -   targets: [ '192.168.1.196:80' ]

rule_files:
    - 'alert.rules'
